[book]
title = "Kubernetes from First Principles"
authors = ["Rajat Arya"]
description = "Why It Works the Way It Does"
src = "docs"
language = "en"

[build]
build-dir = "book"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/rajatarya/kubernetes-first-principles"
edit-url-template = "https://github.com/rajatarya/kubernetes-first-principles/edit/main/docs/{path}"
site-url = "/kubernetes-first-principles/"
no-section-label = false
additional-css = ["docs/theme/custom.css"]
additional-js = ["docs/theme/footer.js", "docs/theme/goatcounter.js", "mermaid.min.js", "mermaid-init.js"]

[output.html.search]
enable = true
limit-results = 30
heading-split-level = 2

[output.html.fold]
enable = true
level = 1
